project:
  type: book
  output-dir: docs

lang: "pt-BR"

book:
  title: "Análise de dados de Metagenômica"
  author: "Dalmolin Systems Biology Group"
  chapters:
    - index.qmd
    - content/01_setup.qmd
    - content/02_qc.qmd
    - content/03_montagem.qmd
    - content/04_taxonomia.qmd
    - content/05_anotacao.qmd
    - content/06_analise_downstream.qmd
  reader-mode: true
  favicon: content/images/dalmolin_icon.svg
  site-url: https://dalmolingroup.github.io/metagenome-course/
  repo-url: https://github.com/dalmolingroup/metagenome-course
  page-footer:
      Análise de Dados de Metagenômica é um curso construído por membros do
      <a href="https://dalmolingroup.imd.ufrn.br/">Dalmolin Group</a>.

knitr:
  opts_chunk:
    message: false
    warning: false
    results: false

format:
  html:
    theme: cosmo
    callout-appearance: simple
    code-link: true
  pdf:
    documentclass: scrreprt
