project:
  type: book
  output-dir: docs

lang: "pt-BR"

book:
  title: "Análise de dados de Metagenômica"
  author: "Dalmolin Systems Biology Group"
  chapters:
    - index.qmd
    - content/01_setup.qmd
    - content/02_qc.qmd
    - content/03_montagem.qmd
    - content/04_taxonomia.qmd
    - content/05_anotacao.qmd
  reader-mode: true
  favicon: content/images/dalmolin_icon.svg
  site-url: https://dalmolingroup.github.io/metagenome-course/
  repo-url: https://github.com/dalmolingroup/metagenome-course
  page-footer:
      Análise de Dados de Metagenômica é um curso construído por membros do
      <a href="https://dalmolingroup.imd.ufrn.br/">Dalmolin Group</a>.

knitr:
  opts_chunk:
    message: false
    warning: false
    results: false

format:
  html:
    theme:
      light: flatly
      dark: darkly
    callout-appearance: simple
    code-link: true
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#b19cd9"
    highlight-style: github
