name: metagenomicsTraining
channels:
  - arthurvinx
  - conda-forge
  - bioconda
  - defaults
  - salilab
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.13
  - annotate=1.0
  - annotated-types=0.7.0
  - aria2=1.37.0
  - attr=2.5.1
  - binutils_impl_linux-64=2.43
  - biopython=1.85
  - bowtie2=2.5.4
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - curl=8.11.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - diamond=2.1.11
  - easel=0.49
  - eggnog-mapper=2.1.12
  - expat=2.6.4
  - fastp=0.24.0
  - fastqc=0.12.1
  - fastx_toolkit=0.0.14
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gawk=5.3.1
  - gcc_impl_linux-64=14.2.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gfortran_impl_linux-64=14.2.0
  - giflib=5.2.2
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmp=6.3.0
  - gnuplot=5.4.10
  - graphite2=1.3.13
  - gsl=2.7
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gxx_impl_linux-64=14.2.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hmmer=3.4
  - hpack=4.1.0
  - htslib=1.21
  - humanfriendly=10.0
  - humanize=4.11.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - isa-l=2.31.1
  - jinja2=3.1.5
  - kaiju=1.10.1
  - kaleido-core=0.2.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - leveldb=1.23
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgd=2.3.3
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libgtextutils=0.7
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.46
  - libpq=17.2
  - libsanitizer=14.2.0
  - libsndfile=1.2.2
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - make=4.4.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mathjax=2.7.7
  - mdurl=0.1.2
  - megahit=1.2.9
  - mmseqs2=17.b804f
  - mpfr=4.2.1
  - mpg123=1.32.9
  - multiqc=1.27.1
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - narwhals=1.26.0
  - natsort=8.4.0
  - ncbi-vdb=3.2.0
  - ncurses=6.5
  - networkx=3.2.1
  - nspr=4.36
  - nss=3.108
  - numpy=2.0.2
  - openjdk=23.0.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - ossuuid=1.6.2
  - packaging=24.2
  - pango=1.56.1
  - pcre2=10.44
  - perl=5.32.1
  - perl-alien-build=2.84
  - perl-alien-libxml2=0.17
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-constant=1.33
  - perl-data-dumper=2.183
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.70
  - perl-ffi-checklib=0.28
  - perl-file-chdir=0.1010
  - perl-file-path=2.18
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-gd=2.83
  - perl-gdgraph=1.54
  - perl-gdgraph-histogram=1.1
  - perl-gdtextutil=0.86
  - perl-importer=0.026
  - perl-mime-base64=3.16
  - perl-parent=0.236
  - perl-path-tiny=0.122
  - perl-pathtools=3.75
  - perl-perlio-gzip=0.20
  - perl-scope-guard=0.21
  - perl-sub-info=0.002
  - perl-term-table=0.024
  - perl-test-nowarnings=1.06
  - perl-test2-suite=0.000163
  - perl-uri=5.12
  - perl-xml-libxml=2.0210
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - pigz=2.8
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - plotly=6.0.0
  - plyvel=1.3.0
  - prodigal=2.6.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyaml-env=1.2.2
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dotenv=1.0.1
  - python-kaleido=0.2.1
  - python_abi=3.9
  - pyyaml=6.0.2
  - qt-main=5.15.15
  - r-base=4.4.2
  - r-cli=3.6.3
  - r-crayon=1.5.3
  - r-data.table=1.16.4
  - r-dplyr=1.1.4
  - r-ellipsis=0.3.2
  - r-fansi=1.0.6
  - r-generics=0.1.3
  - r-glue=1.8.0
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-pillar=1.10.1
  - r-pkgconfig=2.0.3
  - r-purrr=1.0.2
  - r-r6=2.6.0
  - r-rlang=1.1.5
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-withr=3.0.2
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=13.9.4
  - rich-click=1.8.5
  - samtools=1.21
  - sed=4.8
  - setuptools=75.8.0
  - snappy=1.2.1
  - spectra=0.0.11
  - sqlite=3.48.0
  - sra-tools=3.2.0
  - sysroot_linux-64=2.17
  - tiktoken=0.8.0
  - tk=8.6.13
  - tktable=2.10
  - tqdm=4.67.1
  - typeguard=4.4.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wget=1.21.4
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xlsxwriter=3.2.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
